name: CI
on:
  - push
  - pull_request
jobs:
  test:
    name: Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - run: node demo.js
      - uses: actions/github-script@v7
        with:
          script: | #```typescript
            function green(str) { return `\u001B[32m${str}\u001B[39m` }

            console.log(green('console green'));
            core.info(green('core info green'));
          #```

      - run: npm test
